app:
    resource: "@AppBundle/Controller/"
    type: annotation

users:
  resource: '@UsersBundle/Resources/config/routing.yml'

rest:
    resource: '@RestBundle/Resources/config/routing.yml'

admin:
  resource: '@AdminBundle/Resources/config/routing.yml'

acme:
  resource: '@AcmeBundle/Resources/config/routing.yml'


logout:
    path: /logout