services:
    app.mongodb_driver_manager:
        class: MongoDB\Driver\Manager
        arguments: ["%mongodb_host%"]
    app.data_manager:
        class: AppBundle\Data\Manager
        abstract: true
        arguments: ['%mongodb_db_name%', '@app.mongodb_driver_manager']