users_registration:
    path: /users/register
    defaults:  { _controller: UsersBundle:Frontend/Registration:register }

users_registration_fb_callback:
    path: /users/register/fb-callback
    defaults:  { _controller: UsersBundle:Frontend/Registration:fbCallback }