users_login:
    path: /login
    defaults:  { _controller: UsersBundle:Frontend/Security:login }

users_login_check:
    path: /login_check
    defaults: { _controller: UsersBundle:Frontend/Security:loginCheck }
    methods:  [POST]

users_registration:
    path: /registration
    defaults:  { _controller: UsersBundle:Frontend/Security:registration }