services:
    storage.mongo.user:
        class: UsersBundle\Storage\UserMongoStorage
        arguments: ['@mongo_client', '%mongo.storage%']
    repository.user:
        class: UsersBundle\Repository\UserRepository
        arguments: ['@storage.mongo.user']