services:
    users.storage.mongo.user:
        class: UsersBundle\Storage\UserMongoStorage
        arguments: ['@mongo_client', '%mongo.storage%']
    users.repository.user:
        class: UsersBundle\Repository\UserRepository
        arguments: ['@users.storage.mongo.user']
    users.security.form_authenticator:
        class: UsersBundle\Security\FormAuthenticator