parameters:
    mongo.session.options:
        database: blizzard
        collection: session
    mongodb_host: 127.0.0.1
    mongodb_username: ~
    mongodb_password: ~
    mongo.storage:
        database: blizzard


services:
    # ...
    mongo_client:
        class: MongoDB\Driver\Manager
        # if using a username and password
        #arguments: ['mongodb://%mongodb_username%:%mongodb_password%@%mongodb_host%:27017']
        # if not using a username and password
        arguments: ['mongodb://%mongodb_host%:27017']
    blizzard.session.handler.mongo:
        class: BlizzardBundle\Session\Storage\Handler\MongoDbSessionHandler
        arguments: ['@mongo_client', '%mongo.session.options%']
